[tox]
envlist = py310

[testenv]
deps =
    pytest
    coverage
    blspy==2.0.3
commands =
    coverage run --source=electrum_dash --omit=electrum_dash/gui/*,electrum_dash/plugins/*,electrum_dash/scripts/*,electrum_dash/tests/* -m pytest -v
    coverage report
extras =
    tests

[gh-actions]
python =
    3.10: py310
